Build Hello- Microverse
AceMannie/Hello-Microverse pull request #2
Opened 2023-02-23 14:25 UTC by AceMannie

This Pull request ,  I have added the requirements. 

- [x] Add `index.html` file with a header.
- [x] Add `style.css` with a style for the header.  
- [x]  Add `text.md` file that should be ignored by git.
- [x] Created `.gitignore` file and add `text.md `and `node_modules` to it.

Note: This pull request is continuation of previous [pull request](https://github.com/AceMannie/Hello-Microverse/pull/1).

The previous reviewer asked me to create a new branch with a descriptive name, which i have done here.

2023-02-23 15:10 UTC, DuaneDave requested changes
Hi @AceMannie 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
✔️ Good commit history
✔️ Great PR summary
✔️ Correct usage of GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 15:10 UTC, DuaneDave commented on README.md
> +prints Hello Microverse in default browser.
As previously requested, the getting started section and its subsection are supposed to have details that will instruct new users of your projects on what they need and need to know before using your app. Kindly fill in the correct details for the sections to make your documentation more effective.

You can use this [one](https://github.com/Christelle-12/Mobile-project) for reference

2023-02-23 15:10 UTC, DuaneDave commented on README.md
> +Clone this repository to your desired folder and open html file.
The prerequisites section should contain the things a new user should know before being able to use the project. I recommend you include this section correctly to make your readme more effective in instructing a new user using the above-linked readme as a reference.

2023-02-23 15:10 UTC, DuaneDave commented on README.md
> +Dec 28th, 2022
[OPTIONAL] This section is not supposed to be found in the readme but should be the content of a file called LICENSE in your project filesystem. Kindly remove it to declutter the documentation.

2023-02-23 15:10 UTC, DuaneDave commented on README.md
> +This project is [MIT](https://choosealicense.com/licenses/mit/) licensed.
There should be a LICENSE file in your project filesystem and this file will contain what you have added below this line. After including that file, the link to the file is not  `https://choosealicense.com/licenses/mit/` but ./LICENSE. Consider implementing this in order to make the readme more personalized.

2023-02-24 11:20 UTC, AceMannie commented on README.md
> +prints Hello Microverse in default browser.
@DuaneDave  kindly  review the  updated Hello Microverse Project README.md file. 

Thank You.

2023-02-24 16:09 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @AceMannie, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 13:55 UTC, Ibizugbe approved these changes
STATUS: APPROVED 🎉🎉🎉

Hi @AceMannie,

Your project is complete! There is nothing else to say other than... it's time to merge it ☺️
Congratulations! 🎉


Highlights☺️☺️

✔ Linters are passing
✔ Readme file looks good.
✔ Great use of GitHub flow

Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

2023-03-21 15:14 UTC, AceMannie commented
Thank you for reviewing the code @Ibizugbe  to understand you more on the [OPTIONAL] prefix, are you talking about the README.md file in  line 22 -  26? please I'd like some clarifications .

Thank you.

2023-03-21 15:21 UTC, Ibizugbe commented
Hello  @AceMannie , I don't think I dropped any optional suggestion, probably you can point out what you are referring to if there is any form of misunderstanding😉😉

2023-03-21 15:52 UTC, AceMannie commented
@Ibizugbe  Thank you for your response, I understand the project has been approved .

However in the dashboard I'm still seeing a submit button appeared instead of the green complete icon so i thought there's something needed to be done with your comment below .

"Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application."   Can i go ahead and click for submit and merge the pull request?

2023-03-21 15:59 UTC, Ibizugbe commented
@AceMannie , I understand you clearly. When your project is completed, a form will be provided for you to submit the link to your project. When this is submitted, your project is marked completed☺️ with the green badge😉

You can also see before the optional those texts that it was written "no optional suggestions" those texts are there to just let you know more about optional suggestions.. you can kindly ignore it for now.. and take note of it only when you have an "optional suggestion"

Incase you're still confused,  Kindly send a message on slack, then we can proceed to a zoom call if needed.

2023-03-21 16:05 UTC, AceMannie commented
Thank you for the clarity @Ibizugbe  have check the form and submitted . will now close the comment.

2023-03-22 08:40 UTC, merged